(function(){'use strict';var p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");},q=aa(this),ba=function(a,b){if(b)a:{var d=q;a=a.split(".");for(var c=
0;c<a.length-1;c++){var e=a[c];if(!(e in d))break a;d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&b!=null&&p(d,a,{configurable:!0,writable:!0,value:b})}};ba("globalThis",function(a){return a||q});/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
let r=globalThis.trustedTypes,t;function ca(){let a=null;if(!r)return a;try{const b=d=>d;a=r.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var u=class{constructor(a){this.N=a}toString(){return this.N+""}};function v(a){var b;t===void 0&&(t=ca());a=(b=t)?b.createScriptURL(a):a;return new u(a)}function w(a){if(a instanceof u)return a.N;throw Error("");};function y(a,...b){if(b.length===0)return v(a[0]);let d=a[0];for(let c=0;c<b.length;c++)d+=encodeURIComponent(b[c])+a[c+1];return v(d)}function z(a,b){a=w(a).toString();const d=a.split(/[?#]/),c=/[?]/.test(a)?"?"+d[1]:"";return da(d[0],c,/[#]/.test(a)?"#"+(c?d[2]:d[1]):"",b)}
function da(a,b,d,c){function e(g,h){g!=null&&(Array.isArray(g)?g.forEach(k=>e(k,h)):(b+=f+encodeURIComponent(h)+"="+encodeURIComponent(g),f="&"))}let f=b.length?"&":"?";c.constructor===Object&&(c=Object.entries(c));Array.isArray(c)?c.forEach(g=>e(g[1],g[0])):c.forEach(e);return v(a+b+d)}const ea=/[^#]*/;function fa(a){a=w(a).toString();return v(ea.exec(a)[0]+"")};function ha(a){return a.endsWith("/")?a.slice(0,-1):a}y`cs/ta/tag_assistant_api_bin.js`;var ia=y`cs/ta/content_script_bin.js`,ja=y`cs/ta/start_debug_content_script_bin.js`,A=y`cs/ta/start_prod_debug_content_script_bin.js`,ka=y`cs/gf/guided_flows_content_script_bin.js`,B=ha("https://tagassistant.google.com");function la(a){a:{var b=a.type;if(typeof b!=="string")b=!1;else switch(b){case "CLEAR_COOKIE":case "CONTAINER_DETAILS":case "CONTAINER_STARTING":case "LEGACY_CONTAINER_STARTING":case "MEMO":case "END_SESSION":case "PING":case "DEBUG_CONTAINER_FAILED_TO_LOAD":case "NAVIGATE":case "RESEND_MEMOS":case "PAGE_SUMMARY":case "SIDE_PANEL":case "CONNECTION_ISSUE":case "PASSTHROUGH_API":b=!0;break a;default:b=!1}}return b&&a.type==="SIDE_PANEL"};var ma=async function(a){if(a.g.management&&a.g.runtime.id!=="kejbdjndbnbjgmefkgdddjlbokphdefk")try{await a.g.management.get("kejbdjndbnbjgmefkgdddjlbokphdefk")&&await a.g.management.uninstallSelf()}catch(b){}},C=function(a){a.l&&a.g.tabs.get(a.l,b=>{b!=null&&b.windowId&&a.g.windows.update(b.windowId,{focused:!0},()=>{a.g.tabs.update(a.l,{active:!0})})})},na=function(a){a.g.tabs.query({url:"https://*.google.com/embed/tagging/info/sidepanel*"},b=>{for(const d of b)d.id&&a.g.scripting.executeScript({target:{tabId:d.id},
files:["cms/sidepanel/open_side_panel_content_script_compiled.js"]})})},oa=async function(a){const [b]=await a.g.tabs.query({active:!0,lastFocusedWindow:!0});if(b==null?0:b.id)a.l=b.id},pa=function(a){const b=new URL(a.H);b.searchParams.set("opened","true");a.g.tabs.create({url:b.toString(),active:!0},d=>{d.id&&a.u(d.id)})},qa=async function(a,b){var d=D;if(d.l&&d.l===b){var c=a.data,e;switch((e=a.data)==null?void 0:e.type){case "MEMO":let f,g,h;c=c==null?void 0:(f=c.data)==null?void 0:(g=f.memo)==
null?void 0:(h=g.sanitized)==null?void 0:h.messageType;if(c!=="INIT"&&c!=="GTAG_HIT")return;break;default:return}try{await d.g.runtime.sendMessage({type:"onMemoMessage",data:Object.assign({},a,{tabId:b})})}catch(f){}}},sa=class{constructor(){this.g=chrome;this.enableSidePanel=!0;this.H="https://support.google.com/embed/tagging/info/sidepanel";this.P=!1;this.l=this.v=0;ma(this);this.setup()}setup(){this.enableSidePanel&&(this.g.runtime.onMessage.addListener((a,b,d)=>{switch(a.type){case "open_side_panel":let c;
(a=(c=b.tab)==null?void 0:c.id)&&b.url&&(b.url.startsWith(this.H)||ra.test(b.url))&&!this.l?this.u(a):C(this);break;case "open_ta_side_panel":if(!a.tabId)break;this.g.tabs.get(a.tabId,g=>{let h;(h=this.S)==null||h.call(this,g)});break;case "side_panel_context":d({type:"side_panel_context",context:this.o});break;case "start_prod_debug_api":let e;(e=this.B)==null||e.call(this,a.tabId);break;case "end_prod_debug_api":let f;(f=this.B)==null||f.call(this,a.tabId,!0)}}),this.g.runtime.onInstalled.addListener(a=>
{a.reason===this.g.runtime.OnInstalledReason.INSTALL&&this.g.tabs.query({active:!0,lastFocusedWindow:!0},([b])=>{b=b==null?void 0:b.url;var d;if(d=b)if(this.P)d=!0;else{d=new URL(b);var c=RegExp("chrome-extension:\\/\\/([^\\/]+)"),e;c=(e=this.g.runtime.getURL("/").match(c))==null?void 0:e[1];d=b.startsWith("https://chromewebstore.google.com/detail")&&!!c&&d.pathname.endsWith(c)&&d.searchParams.get("side_panel")==="true"}if(d){if(e=(new URL(b)).searchParams.get("context"))this.o=e;e=new URL(this.H);
e.searchParams.set("installed","true");this.o&&e.searchParams.set("context",this.o);this.g.tabs.create({url:e.toString(),active:!0})}});na(this)}),this.g.runtime.onConnect.addListener(a=>{a.name==="sidePanel"&&(this.l||(this.A(),oa(this)),a.onMessage.addListener(b=>{this.v||b.type!=="connect_side_panel"||(this.v=setTimeout(()=>{this.v=0;a.postMessage({type:"side_panel_connected"})},25E3))}),a.onDisconnect.addListener(()=>{this.F();this.l=0;this.o=void 0;this.v&&clearTimeout(this.v);let b;(b=this.B)==
null||b.call(this,0,!0)}))}),this.g.runtime.onMessageExternal.addListener((a,b,d)=>{switch(a==null?void 0:a.type){case "connect_side_panel":d({type:"side_panel_connected"});break;case "open_side_panel":if(this.l)C(this);else{a.context&&(this.o=a.context);var c;a.openInSameTab&&(b==null?0:(c=b.tab)==null?0:c.id)?this.u(b.tab.id):pa(this)}}}))}u(a){this.A();this.g.sidePanel.setOptions({enabled:!0,tabId:a,path:`${"cms/sidepanel/sidepanel.html"}?time=${Date.now()}`});this.g.sidePanel.open({tabId:a},()=>
{this.l=a})}A(){this.g.scripting.registerContentScripts([{id:"ct-sidepanel",matches:["<all_urls>"],js:E,runAt:"document_start",allFrames:!0}]);this.o&&this.g.tabs.query({currentWindow:!0},a=>{for(const b of a){let d;b.id&&((d=b.url)==null?0:d.startsWith("http"))&&this.g.scripting.executeScript({target:{allFrames:!0,tabId:b.id},files:E})}})}F(){this.g.scripting.unregisterContentScripts({ids:["ct-sidepanel"]})}},E=["cms/polyfills/webcomponents-ce.js",ka.toString()],ra=RegExp("https?://[^/:]*\\.google\\.com(:\\d+)?/guided_flows/open*");async function ta(a){try{return(await fetch(a,{method:"HEAD",mode:"no-cors",cache:"no-store"})).status<400}catch(b){return!1}};async function ua(a){try{const b=await a.i18n.getUILanguage();if(b)return b}catch(b){}};const F=Array.from("\ud83d\udd37\ud83d\udfe1\ud83d\udfea\ud83d\udfe9\ud83d\udd35\ud83d\udd36\ud83d\udfe2\ud83d\udfe3\ud83d\udfe6\ud83d\udfe8");
var va=function(a){a.g.action.onClicked.addListener(b=>{a.u(b)})},xa=function(a){if(a.g.runtime.id!=="kejbdjndbnbjgmefkgdddjlbokphdefk"){var b=a.g.runtime.getManifest().version;setTimeout(()=>{a.g.runtime.onUpdateAvailable.addListener(d=>{wa(a,d,b)})},2E3)}},ya=async function(a){await G(a,"ta_content_script",ia.toString())},H=function(a,b,d,c,e){var f=b.frames.get(d);f==null&&(e!=null?a=e:(f=F[a.D],a.D++,a.D>=F.length&&(a.D=0),a=f),f={port:c,emoji:a},b.frames.set(d,f));c!=null&&(f.port=c);e!=null&&
(f.emoji=e);return f},L=function(a,b,d={}){let c=a.h.get(b);if(c==null){c={m:new Set};var e;if(!(e=a.h.size===0))a:{for(const [f]of a.h)if(!a.i.has(f)){e=!1;break a}e=!0}e&&(I(a),d.C&&a.A());a.h.set(b,c);J(a);K(a,b)}return c},O=function(a,b,d,c,e,f){e.m.add(b);(e=a.i.get(b))?M(e,c):(e=N(c,d),b===c&&(e.j=0),a.i.set(b,e),za(a,b,d));e.R=!!f;return e},T=function(a,b,d){let c,e;const f=d!=null?d:(c=b.sender)==null?void 0:(e=c.tab)==null?void 0:e.id;if(f!=null){console.log("Got connection from Tag Assistant on tab %s \n",
f);K(a,f);var g=b.name==="TA_EXT_PORT_SIDE_PANEL",h=L(a,f,{C:!g});h.port=b;var k;h.url=(k=b.sender)==null?void 0:k.url;if(h.J){const l=h.J;setTimeout(()=>{P(a,l)},300);h.J=void 0}b.onMessage.addListener(l=>{a.h.has(f)||(a.h.size===0&&(I(a),g||a.A()),a.h.set(f,h),J(a),K(a,f));if(la(l.data)){var m=!1;switch(l.data.subType){case "sp_open_ta":Aa(a,f);m=!0;break;case "sp_guided_install":m=btoa(JSON.stringify({entryPoint:"ta_side_panel"}));var n;(n=a.O)==null||n.call(a,f,m);m=!0}if(m)return}l.data.type===
"CONTAINER_DETAILS"?(n=l.data.data.nonce,m=a.G.get(n),a.G.delete(n),Q(l,m)):h.m.forEach(x=>{R(a,x,l,g)})});b.onDisconnect.addListener(()=>{h.port===b&&(console.log("port to Tag Assistant tab %s closed",f),h.port=void 0);const l=a.i.get(f);!l||d&&!l.tagAssistantTabIds.includes(d)||(S(l,f),d&&(R(a,f,{type:"PIPE_MESSAGE",origin:"*",dId:"",tId:0,source:"EXTENSION",data:{type:"SIDE_PANEL",subType:"sp_off",uId:""}},!0),a.h.delete(f),a.h.size===0&&G(a,"ta_prod_debug_attribute_content_script",A.toString(),
[0])))})}},Ba=async function(a,b){let d;try{var c;let e;d=new URL((e=(c=b.sender)==null?void 0:c.url)!=null?e:"")}catch(e){console.log("=== onTagAssistantSidePanelConnect invalid url");console.log(e);return}c=Number(d.searchParams.get("tabId"));!isNaN(c)&&c&&(console.log("Got connection from sidePanel Tag Assistant on tab %s \n",c),T(a,b,c),b=a.h.get(c),O(a,c,d.toString(),c,b).I=1,U(a,c))},Ca=function(a,b){var d;let c;const e=(d=b.sender)==null?void 0:(c=d.tab)==null?void 0:c.id;let f;d=(f=b.sender)==
null?void 0:f.frameId;if(e!=null&&d!=null){K(a,e);var g=a.i.get(e);g==null&&(g=N(),g.j=0,a.i.set(e,g));var h=H(a,g,d,b);b.onMessage.addListener(k=>{a.L.forEach(n=>{n(k,e)});if(g.tagAssistantTabIds.length){var l=k.data.type;l==="CONTAINER_STARTING"&&a.G.set(k.data.data.nonce,h);k.data.emoji=h.emoji;k.source="EXTENSION";k.data.uniqueId=g.uniqueId;k.data.uId=`${g.uniqueId}|${k.dId}`;if(l==="PAGE_SUMMARY")var m=k.data.data.groupId;else l==="MEMO"&&(m=k.data.data.memo.sanitized.key.groupId);if(m&&g.uniqueId){if((l=
a.K[m])&&l!==g.uniqueId)return;a.K[m]=g.uniqueId}m=new Set;for(const n of g.tagAssistantTabIds){l=a.h.get(n);let x;((x=l)==null?0:x.port)&&m.add(l.port)}for(const n of m)n.postMessage(k)}});b.onDisconnect.addListener(()=>{h.port===b&&(h.port=void 0)})}},W=function(a,b,d,c,e,f){if(V(c))return!0;d=(e==null?0:e.length)?e[0]:d;e=a.h.get(d);if(e==null||!e.port)return!1;O(a,b,c,d,e,f);return!0},Q=function(a,b){b!=null&&b.port&&(a.data.emoji=b.emoji,a.source="EXTENSION",b.port.postMessage(a))},X=function(a,
b,d){for(const c of a.h.values())if(c.m.has(b)){let e;(e=c.port)==null||e.postMessage(d)}},Da=function(a,b,d){let c=a.i.get(b);c||(c=N(void 0,d),c.j=0,a.i.set(b,c));return c},Ea=function(a,b,d=!1){if(b.id!=null){var c=void 0;b.url&&(c=new URL(b.url),c=encodeURIComponent(c.href));c=new Map([["tabId",`${b.id}`],["url",c]]);d&&c.set("flowType","guidedFlows");d=z(y`ta_side_panel/index.html`,c);a.g.sidePanel.setOptions({enabled:!0,tabId:b.id,path:d.toString()});a.g.sidePanel.open({tabId:b.id},()=>{})}},
K=function(a,b){a.g.tabs.update(b,{autoDiscardable:!1})},P=async function(a,b){await a.g.tabs.reload(b)},I=function(a){a.M==null&&(a.M=setInterval(()=>{a.g.runtime.getManifest()},15E3))},J=function(a){a.g.storage.local.set({lastTaConnectedTimestamp:Date.now()})},Aa=async function(a,b){const d=a.i.get(b);if(d){d.j=2;var c=d.tagAssistantTabIds.filter(l=>l!==b)[0];if(c)try{var e=await a.g.tabs.get(c);if(e&&e.id){await a.g.windows.update(e.windowId,{focused:!0});await a.g.tabs.update(e.id,{active:!0});
await P(a,b);return}}catch(l){}c=await a.g.tabs.get(b);e=c.index;var f=c.windowId,g=c.url,h=v(B);g=new Map([["restart_tag_assistant","1"],["utm_source","sp_new_tab"],["tabId",`${b}`],["sp_origin",g?`${(new URL(g)).origin}`:""],["extensionId",a.g.runtime.id]]);var k=await ua(a.g);k&&g.set("hl",k);h=fa(z(h,g));c=await a.g.tabs.create({url:h.toString(),active:!0,index:e,windowId:f,openerTabId:c.id});c.id&&(a=L(a,c.id,{C:!0}),a.J=b,a.m.add(b),M(d,c.id))}},R=function(a,b,d,c){if(a=a.i.get(b))d.data.type===
"CLEAR_COOKIE"?a.j=0:a.j!==0||c||(a.j=1),a.frames.forEach(e=>{Q(d,e)})},G=async function(a,b,d,c=[0,1],e){let f=!0;(await a.g.scripting.getRegisteredContentScripts({ids:[b]})).length!==0&&(c.includes(0)?await a.g.scripting.unregisterContentScripts({ids:[b]}):c.includes(1)&&(f=!1));f&&c.includes(1)&&await a.g.scripting.registerContentScripts([{id:b,allFrames:!0,js:[d],matches:["<all_urls>"],excludeMatches:"*://www.googletagmanager.com/static/service_worker/* *://googletagmanager.com/static/service_worker/* *://tagassistant.google.com/ *://tagassistant.google.com/* *://td.doubleclick.net/* *://*.fls.doubleclick.net/*".split(" "),
runAt:"document_start"}]);e==null||e()},U=function(a,b){G(a,"ta_prod_debug_attribute_content_script",A.toString(),[1],()=>{P(a,b)})},za=async function(a,b,d){if(!await ta(d)){var c=a.i.get(b),e;X(a,b,{type:"PIPE_MESSAGE",source:"EXTENSION",origin:"*",tId:b,dId:(e=c==null?void 0:c.parentDocumentId)!=null?e:"",data:{type:"CONNECTION_ISSUE",data:{issues:[{type:7}],pageUrl:d},uniqueId:c==null?void 0:c.uniqueId,uId:""}})}},wa=async function(a,b,d){b.version!==d&&await Fa(a)&&a.g.runtime.reload()},Fa=async function(a){if(a.h.size)return!1;
a=await a.g.storage.local.get(["lastTaConnectedTimestamp"]);let b;a=Number((b=a.lastTaConnectedTimestamp)!=null?b:0);return!a||Number.isNaN(a)||Date.now()-a>18E5?!0:!1},Ga=class{constructor(){this.g=chrome;this.h=new Map;this.i=new Map;this.D=0;this.K={};this.G=new Map;this.L=[];va(this);xa(this);this.F();ya(this);this.g.runtime.onMessage.addListener((a,b,d)=>{let c;if(!(b==null?0:(c=b.tab)==null?0:c.id)){let g;(b==null?0:(g=b.origin)==null?0:g.includes("google.com"))&&b.origin.includes("tagassistant")&&
d(void 0)}else if(a.type==="CHECK_DEBUG"){var e=this.i.get(b.tab.id);let g;var f=Object.assign({},a,{source:"EXTENSION",startDebug:!1,startProdDebug:!1,tabId:b.tab.id,topDocumentId:(g=e==null?void 0:e.parentDocumentId)!=null?g:""});e&&(f.startDebug=Y(e.j),a=!a.referrer&&V(b.url),!e.R&&a&&e.j!==2&&(f.startDebug=!1,e.j=0),f.startProdDebug=Y(e.I));f.tagAssistantTabIds=e==null?void 0:e.tagAssistantTabIds;e!=null&&e.tagAssistantTabIds.length&&b&&b.frameId!=null&&(b=H(this,e,b.frameId),f.emoji=b.emoji);
d(f)}else if(a.type==="RECONNECT")for(f of a.tagAssistantTabIds)if(d=L(this,f,{C:!0}),d=O(this,b.tab.id,b.tab.url||b.tab.pendingUrl||"",f,d),((e=b)==null?void 0:e.frameId)!=null&&a.emoji){let g;H(this,d,(g=b)==null?void 0:g.frameId,void 0,a.emoji)}});this.g.runtime.onConnectExternal.addListener(a=>{a.name==="TAG_ASSISTANT_EXTENSION_PORT"&&T(this,a);a.name==="TA_EXT_PORT_SIDE_PANEL"&&Ba(this,a)});this.g.runtime.onConnect.addListener(a=>{Ca(this,a)});this.g.webNavigation.onCreatedNavigationTarget.addListener(({tabId:a,
sourceTabId:b,url:d})=>{var c=new URL(d);c.hostname.endsWith(".google.com")&&c.searchParams.get("restart_tag_assistant")!=null?(this.h.has(b)||((c=this.i.get(b))?(M(c,a),c.j=1):this.i.set(b,N(a,d)),L(this,a,{C:!0}).m.add(b)),c=!0):c=!1;c||W(this,a,b,d)||(c=this.i.get(b),c!=null&&c.tagAssistantTabIds.length&&Y(c.j)&&W(this,a,b,d,c.tagAssistantTabIds,!0))});this.g.tabs.onUpdated.addListener((a,b,d)=>{if(a=this.i.get(a))a.url=d.url});this.g.tabs.onRemoved.addListener(a=>{var b=this.h.get(a);if(b){this.h.delete(a);
for(var d of b.m){const f=this.i.get(d);if(f)for(const g of f.frames.values()){let h,k;Q({type:"PIPE_MESSAGE",source:"EXTENSION",origin:b.url?(new URL(b.url)).origin:"*",tId:a,dId:(k=(h=f)==null?void 0:h.parentDocumentId)!=null?k:"",data:{type:"CONNECTION_ISSUE",data:{issues:[{type:1}],pageUrl:f.url||""},uId:""}},g)}f&&(f.j=0,S(f,a))}this.h.size===0&&(clearInterval(this.M),this.F())}b=this.i.get(a);this.i.delete(a);d=!1;let c;for(const f of this.h.values())if(f.m.has(a)){c=f;d=f.m.size===1;break}if(c){var e;
X(this,a,{type:"PIPE_MESSAGE",source:"EXTENSION",origin:"*",tId:a,dId:(e=b==null?void 0:b.parentDocumentId)!=null?e:"",data:{type:"CONNECTION_ISSUE",data:{issues:[{type:2,allDebugTabsClosed:d}],pageUrl:(b==null?void 0:b.url)||""},uId:""}});c.m.delete(a)}});this.g.webNavigation.onCommitted.addListener(({tabId:a,frameId:b,url:d,documentId:c})=>{const e=new URL(d),f=e.origin===B;var g=Number(e.searchParams.get("tabId"));const h=this.h.has(g);if(e.pathname==="/login/success"&&h&&f){let k;b=(k=e.searchParams.get("authuser"))!=
null?k:"0";this.g.tabs.remove(a,()=>{});a=new Map([["tabId",`${g}`],["authuser",`${b}`],["rand",`${Math.floor(Math.random()*1E4)}`]]);a=z(y`ta_side_panel/index.html`,a);this.g.sidePanel.setOptions({enabled:!0,tabId:g,path:a.toString()})}else e.origin!=="https://tagassistant.google.com"&&(g=Da(this,a,d),c&&d.startsWith("http")&&b===0&&(g.parentDocumentId=c),b===0&&(a=this.h.get(a),g&&a&&(g.uniqueId=g.uniqueId==null?1:++g.uniqueId)))});this.g.runtime.onMessageExternal.addListener((a,b,d)=>{switch(a==
null?void 0:a.type){case "open_side_panel":case "connect_side_panel":case "side_panel_connected":case "side_panel_context":case "list_tags":case "list_tags_off":case "open_ta_side_panel":case "start_prod_debug_api":case "end_prod_debug_api":break;default:d({})}})}async A(){await G(this,"ta_debug_attribute_content_script",ja.toString())}async F(){(await this.g.scripting.getRegisteredContentScripts({ids:["ta_debug_attribute_content_script"]})).length!==0&&await this.g.scripting.unregisterContentScripts({ids:["ta_debug_attribute_content_script"]})}u(a,
b){Ea(this,a,b)}B(a,b){if(b)this.h.size===0&&G(this,"ta_prod_debug_attribute_content_script",A.toString(),[0]);else if(b=this.i.get(a))b.I=1,U(this,a)}};function N(a,b){return{tagAssistantTabIds:a?[a]:[],frames:new Map,j:1,I:0,url:b}}function M(a,b){a.tagAssistantTabIds.includes(b)||a.tagAssistantTabIds.push(b)}function S(a,b){a.tagAssistantTabIds=a.tagAssistantTabIds.filter(d=>d!==b)}function Y(a){switch(a){case 1:case 2:return!0;case 0:return!1;default:return!1}}
const Ha=["support","developers","tagmanager"];function V(a){if(!a)return!1;try{const b=new URL(a);return b.host.match(/\.?google.co(m|(\.[a-z]{2}))/)||b.host.match(/\.?youtube.co(m|(\.[a-z]{2}))/)?Ha.includes(b.host.split(".")[0]):!1}catch(b){return!1}};self.oninstall=()=>self.skipWaiting();const Z=new Ga,D=new sa;Z.O=(a,b)=>{var d=D;d.l?C(d):(d.o=b,d.u(a))};Z.L.push((a,b)=>{qa(a,b)});D.S=(a,b)=>{Z.u(a,b)};D.B=(a,b)=>{Z.B(a,b)};}).call(this);
