(function(){'use strict';var f=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},g=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},h=g(this),l=function(a,b){if(b)a:{var c=h;a=a.split(".");for(var d=
0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&f(c,a,{configurable:!0,writable:!0,value:b})}};l("globalThis",function(a){return a||h});/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
let m=globalThis.trustedTypes,n;function p(){let a=null;if(!m)return a;try{const b=c=>c;a=m.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var q=class{constructor(a){this.j=a}toString(){return this.j+""}};function r(a){var b;n===void 0&&(n=p());a=(b=n)?b.createScriptURL(a):a;return new q(a)}function t(a){if(a instanceof q)return a.j;throw Error("");};var u=class{constructor(a){this.m=a}toString(){return this.m}};class v{constructor(a){this.l=a}}const z=new v(a=>a.indexOf("chrome-extension://")===0||a.indexOf("moz-extension://")===0||a.indexOf("ms-browser-extension://")===0||a.indexOf("safari-web-extension://")===0);function A(a,...b){if(b.length===0)return r(a[0]);let c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return r(c)};var B=A`cs/ta/tag_assistant_api_bin.js`;A`cs/ta/content_script_bin.js`;A`cs/ta/start_debug_content_script_bin.js`;A`cs/ta/start_prod_debug_content_script_bin.js`;A`cs/gf/guided_flows_content_script_bin.js`;var C=function(a,b,c){switch(b){case "1":a.g.document.documentElement.setAttribute("data-tag-assistant-present",c);break;case "2":a.g.document.documentElement.setAttribute("data-tag-assistant-prod-present",c)}},D=function(a,b){a.g.document.addEventListener("__TA_CS_DOM_EVENT",()=>{b()})},E=class{constructor(a){this.g=a}};function F(a){a=a.runtime.getURL(t(B).toString());a:{var b=[z];if(a instanceof u)b=a;else{for(let c=0;c<b.length;++c){const d=b[c];if(d instanceof v&&d.l(a)){b=new u(a);break a}}b=void 0}}if(!b)throw Error('"'+a+'" is not an extension URL.');return r(a)};function G(a=document){let b;const c=(b=a.querySelector)==null?void 0:b.call(a,"script[nonce]");return c==null?"":c.nonce||c.getAttribute("nonce")||""};function H(a,b){a.src=t(b);(b=G(a.ownerDocument))&&a.setAttribute("nonce",b)};var I=function(a){a.i.runtime.sendMessage({type:"CHECK_DEBUG",source:"PAGE",referrer:a.g.document.referrer},b=>{if(b){a.topDocumentId=b.topDocumentId;a.tabId=b.tabId;var c=b.startDebug;c?(a.tagAssistantTabIds=b.tagAssistantTabIds,a.emoji=b.emoji,C(a.h,"1",String(Date.now()))):C(a.h,"1","");b.startProdDebug?C(a.h,"2",String(Date.now())):C(a.h,"2","");var d=a.h;b=new CustomEvent("TADebugSignal",{detail:{startDebug:c,startProdDebug:!!b.startProdDebug}});d.g.document.dispatchEvent(b)}})},L=function(a){a.port||
(a.port=a.i.runtime.connect(),a.port.onDisconnect.addListener(()=>{J(a)}),K(a))},M=function(a){const b=a.g.document.createElement("script");H(b,F(a.i));a.g.document.documentElement.appendChild(b);b.remove();a.g.document.addEventListener("__TAG_ASSISTANT_API_MESSAGE",c=>{var d=c.detail;a:{var e=d==null?void 0:d.type;if(typeof e!=="string")e=!1;else switch(e){case "API_INSTALLED":case "CHECK_DEBUG":case "DISCONNECT":case "PIPE_MESSAGE":case "RECONNECT":case "WINDOWS_CLOSED":e=!0;break a;default:e=!1}}if(e)a:if(d=
d==null?void 0:d.source,typeof d!=="string")e=!1;else switch(d){case "PAGE":case "EXTENSION":e=!0;break a;default:e=!1}if(e&&(c=c.detail,c.source==="PAGE"))switch(c.type){case "API_INSTALLED":L(a);break;case "PIPE_MESSAGE":c.origin=a.g.origin;var k=c.data;k.type==="PAGE_SUMMARY"&&(k.data.emoji=a.emoji);let w;c.dId=(w=a.topDocumentId)!=null?w:"";let x;c.tId=(x=a.tabId)!=null?x:0;let y;(y=a.port)==null||y.postMessage(c);break;case "DISCONNECT":(k=a.port)==null||k.disconnect(),a.port=void 0}})},J=function(a,
b=!1){let c;if(((c=a.tagAssistantTabIds)==null?0:c.length)||b)if(b)a.port=void 0,L(a);else{let d;a.port&&((d=a.tagAssistantTabIds)==null?0:d.length)&&(a.port=void 0,a.i.runtime.sendMessage({type:"RECONNECT",tagAssistantTabIds:a.tagAssistantTabIds,emoji:a.emoji,source:"PAGE"}),L(a))}else a.port=void 0},K=function(a){let b;(b=a.port)==null||b.onMessage.addListener(c=>{a.g.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:c}))})};new class{constructor(){var a=window;this.i=chrome;this.g=a;this.h=new E(this.g);D(this.h,()=>{I(this)});L(this);M(this);a.addEventListener("pageshow",b=>{b.persisted&&J(this,!0)})}};}).call(this);
