(function(){'use strict';var h=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a},k=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");},m=k(this),n=function(a,b){if(b)a:{var d=m;a=a.split(".");for(var c=
0;c<a.length-1;c++){var e=a[c];if(!(e in d))break a;d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&b!=null&&h(d,a,{configurable:!0,writable:!0,value:b})}};n("globalThis",function(a){return a||m});n("Promise.withResolvers",function(a){return a?a:function(){var b,d;return{promise:new Promise(function(c,e){b=c;d=e}),resolve:b,reject:d}}});/*


 Copyright (c) 2015-2018 Google, Inc., Netflix, Inc., Microsoft Corp. and contributors
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var p=class extends Error{constructor(a){super(a?`${a.length} errors occurred during unsubscription:
${a.map((b,d)=>`${d+1}) ${b.toString()}`).join("\n  ")}`:"");this.errors=a;Object.setPrototypeOf(this,new.target.prototype);this.name="UnsubscriptionError"}};function q(a,b){a&&(b=a.indexOf(b),0<=b&&a.splice(b,1))};function r(a){return typeof a==="function"};var t=class{constructor(){this.v=void 0;this.closed=!1;this.h=this.g=null}unsubscribe(){let a;if(!this.closed){this.closed=!0;const d=this.g;if(Array.isArray(d))for(var b of d)b.remove(this);else d==null||d.remove(this);b=this.v;if(r(b))try{b()}catch(e){a=e instanceof p?e.errors:[e]}const c=this.h;if(c){this.h=null;for(const e of c)try{r(e)?e():e.unsubscribe()}catch(g){let f;a=(f=a)!=null?f:[];g instanceof p?a=[...a,...g.errors]:a.push(g)}}if(a)throw new p(a);}}add(a){if(a&&a!==this)if(this.closed)r(a)?
a():a.unsubscribe();else{if(a instanceof t){if(a.closed||a.o(this))return;a.m(this)}let b;(this.h=(b=this.h)!=null?b:[]).push(a)}}o(a){const b=this.g;return b===a||Array.isArray(b)&&b.includes(a)}m(a){const b=this.g;this.g=Array.isArray(b)?(b.push(a),b):b?[b,a]:a}u(a){const b=this.g;b===a?this.g=null:Array.isArray(b)&&q(b,a)}remove(a){const b=this.h;b&&q(b,a);a instanceof t&&a.u(this)}},u=t;const v=new t;v.closed=!0;u.EMPTY=v;/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
let w=globalThis.trustedTypes,x;function y(){let a=null;if(!w)return a;try{const b=d=>d;a=w.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var z=class{constructor(a){this.l=a}toString(){return this.l+""}};function A(a){var b;x===void 0&&(x=y());a=(b=x)?b.createScriptURL(a):a;return new z(a)}function B(a){if(a instanceof z)return a.l;throw Error("");};function C(a,...b){if(b.length===0)return A(a[0]);let d=a[0];for(let c=0;c<b.length;c++)d+=encodeURIComponent(b[c])+a[c+1];return A(d)}function D(a,b,d,c){function e(f,l){f!=null&&(Array.isArray(f)?f.forEach(E=>e(E,l)):(b+=g+encodeURIComponent(l)+"="+encodeURIComponent(f),g="&"))}let g=b.length?"&":"?";c.constructor===Object&&(c=Object.entries(c));Array.isArray(c)?c.forEach(f=>e(f[1],f[0])):c.forEach(e);return A(a+b+d)}const F=/[^#]*/;function G(a){return a.endsWith("/")?a.slice(0,-1):a}C`cs/ta/tag_assistant_api_bin.js`;C`cs/ta/content_script_bin.js`;C`cs/ta/start_debug_content_script_bin.js`;C`cs/ta/start_prod_debug_content_script_bin.js`;C`cs/gf/guided_flows_content_script_bin.js`;var H=G("https://tagassistant.google.com/embedded/side_panel");async function I(a){try{const b=await a.i18n.getUILanguage();if(b)return b}catch(b){}};var J={C:0,A:1,B:2,0:"FORMATTED_HTML_CONTENT",1:"EMBEDDED_INTERNAL_CONTENT",2:"EMBEDDED_TRUSTED_EXTERNAL_CONTENT"},K=class extends Error{constructor(a){super(`${a} cannot be used with intent ${J[1]}`);this.type=a;this.intent=1;this.name="TypeCannotBeUsedWithIframeIntentError"}};var M=async function(){await (new L).init()},N=async function(a){const b=a.document.querySelector("iframe");if(b){var d=new URLSearchParams(a.window.location.search);var c=Number(d.get("tabId"));var e=d.get("url");var g=d.get("isWebdriverTest");var f=d.get("authuser");d=d.get("flowType");c=isNaN(c)?void 0:{tabId:c,url:e,D:g,i:f,flowType:d};if(c&&(g=A(H))){e=encodeURIComponent(a.j.runtime.getManifest().version);e=new Map([["origin",a.window.origin],["utm_source","side_panel"],["tabId",`${c.tabId}`],
["ext_version",`${e}`]]);c.i&&e.set("authuser",c.i);c.flowType&&e.set("flowType",c.flowType);(a=await I(a.j))&&e.set("hl",a);f=B(g).toString();d=f.split(/[?#]/);const l=/[?]/.test(f)?"?"+d[1]:"";a=d[0];g=l;f=/[#]/.test(f)?"#"+(l?d[2]:d[1]):"";a=D(a,g,f,e);c.url?(c=`url=${c.url}`,a=B(a).toString(),c=A(F.exec(a)[0]+(c.trim()?"#"+c:""))):c=a;b.removeAttribute("srcdoc");if(!(c instanceof z))throw new K(typeof c);a="allow-same-origin allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation".split(" ");
b.setAttribute("sandbox","");for(e=0;e<a.length;e++)b.sandbox.supports&&!b.sandbox.supports(a[e])||b.sandbox.add(a[e]);b.src=B(c).toString()}}},L=class{constructor(){var a=window,b=chrome;this.document=document;this.window=a;this.j=b}async init(){const a=Promise.withResolvers();this.document.addEventListener("DOMContentLoaded",()=>{a.resolve(!0)});await a.promise&&N(this)}};(async()=>{await M()})();}).call(this);
